server:
  port: 8989 #端口号
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库url
    url: jdbc:mysql://localhost:3306/sg_blog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    # 数据库访问账户
    username: root
    # 数据库访问密码
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  redis:
    port: 6379
    password: redis@12345!
    host: 43.136.173.216
    database: 1
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag #逻辑删除字段
      logic-delete-value: 1 #逻辑删除值
      logic-not-delete-value: 0
      id-type: auto # 按数据库配置自增id
oss:
  accessKey: 58-TEQR0Ki4Fv2IJjVISjy4hcScdNDnyj6VKYaFX
  secretKey: 9Q0_5crY3rey8_ZgRvQYLBB_PoGmICImzPhLve0V
  bucket: zhejiang-bucket
  domain: http://rqpvuizzf.hd-bkt.clouddn.com/
